### ISSUE TITLE
Falta wireframe del Login

### ISSUE THREAD

**Issue by Piarrot** [1022FSNSANCN02ARED/grupo-04#2]
Hola Grupo! Cómo dice el titulo, estaria faltandonos el wireframe de esa pantalla!

**Comment by marixxa** [comment]
Hola Pablo, este wirwframe ya fue agregado en su momento, porqué dice "critical" acá??

**Comment by Piarrot** [comment]
@marixxa  porque era algo requerido para la entrega del primer sprint!
Marco como resuelto!
